---
- hosts: all
  any_errors_fatal: true
  gather_facts: true
  gather_timeout: 86400
  vars_files:
    - /tmp/{{CLUSTER_NAME}}.yml
    - vars.yml

  roles:
     - role: mysql
       when: groups['mysql'] is defined and inventory_hostname in groups['mysql']
     - role: kdc
       when: groups['kdcserver'] is defined
     - { role: ambari }
