-
  hosts: mysql
  gather_facts: yes
  vars:
     mysql_root_password: "{{ MYSQL_ROOT_PASSWORD }}"
     mysql_databases:
       - name: "{{MYSQL_DATABASE_NAME}}"
         encoding: utf8
         collation: utf8_general_ci
     mysql_users:
       - name: "{{MYSQL_USERNAME}}"
         host: "%"
         password: "{{MYSQL_PASSWORD}}"
         priv: "{{MYSQL_USERNAME}}.*:ALL"

  roles:
    - mysql
